### ISSUE TITLE
[UI Proposal] Hyperlink activity! 

### ISSUE THREAD

**Issue by glasgowm148** [paideiadao/paideia-app#107] opened 2023-11-21 12:05 UTC
Might already be an issue for this but wasn't able to find it via search

These should all be hyperlinked, it's probably one of the first things everyone will try and do.

![Screenshot 2023-11-21 at 12 04 33](https://github.com/paideiadao/paideia-app/assets/19927264/8308ae60-da39-42ae-a13c-15d3717e16e9)

Likewise, they should be hyperlinked on the full latest activity page too.

**Comment by glasgowm148** [comment] 2023-11-21 12:06
and in User Activity too
![Screenshot 2023-11-21 at 12 06 28](https://github.com/paideiadao/paideia-app/assets/19927264/f744573f-5050-4ece-afb6-3fb293ea33fd)

**Comment by esot321c** [comment] 2023-11-23 20:35
Duplicate of https://github.com/paideiadao/paideia-app/issues/18

**Closed by esot321c** 2023-11-23 20:35 UTC
Labels: duplicate
