### ISSUE TITLE
UI Proposal: Proposal/Discussion names should be clickable links

### ISSUE THREAD

**Issue by FlyingPig69** [paideiadao/paideia-app#64] opened 2023-10-04 13:46 UTC
Improved user experience as users will instinctively click the title itself rather than the "View" link.

![image](https://github.com/paideiadao/paideia-app/assets/124304224/2ac72605-ffa8-46b3-b80e-ae244817e0f2)

**Comment by esot321c** [comment] 2023-10-10 18:03
Duplicate of https://github.com/paideiadao/paideia-app/issues/71

**Closed by esot321c** 2023-10-10 18:03 UTC
Labels: duplicate
